steps:
  # Build the container image with build args
  # CRITICAL: NEXT_PUBLIC_* vars are baked into the JS bundle at build time by Next.js
  # They MUST be passed as --build-arg or client-side code won't have them
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_BETTER_AUTH_URL=${_NEXT_PUBLIC_BETTER_AUTH_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_COINGECKO_API_KEY=${_NEXT_PUBLIC_COINGECKO_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_NEWS_API_KEY=${_NEXT_PUBLIC_NEWS_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GA_MEASUREMENT_ID=${_NEXT_PUBLIC_GA_MEASUREMENT_ID}'
      - '--build-arg'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      # Server-side vars needed at build time for auth.ts initialization
      - '--build-arg'
      - 'BETTER_AUTH_URL=${_BETTER_AUTH_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/financial-planner:latest'
      - '.'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/financial-planner:latest'

  # Deploy to Cloud Run with Secret Manager integration
  # SECURITY: Sensitive secrets are now mounted from Secret Manager instead of env vars
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'financial-planner'
      - '--image'
      - 'gcr.io/$PROJECT_ID/financial-planner:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Non-sensitive environment variables (also needed at runtime for server-side code)
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY},NEXT_PUBLIC_BETTER_AUTH_URL=${_NEXT_PUBLIC_BETTER_AUTH_URL},NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL},NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL},NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY},NEXT_PUBLIC_COINGECKO_API_KEY=${_NEXT_PUBLIC_COINGECKO_API_KEY},NEXT_PUBLIC_NEWS_API_KEY=${_NEXT_PUBLIC_NEWS_API_KEY},NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY},NEXT_PUBLIC_GA_MEASUREMENT_ID=${_NEXT_PUBLIC_GA_MEASUREMENT_ID},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},BETTER_AUTH_URL=${_BETTER_AUTH_URL},SECRET_MANAGER_PROJECT_ID=$PROJECT_ID'
      # Mount sensitive secrets from Google Secret Manager
      # These secrets must be created in Secret Manager before deployment
      - '--update-secrets'
      - 'GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,BETTER_AUTH_SECRET=BETTER_AUTH_SECRET:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,SUPABASE_DATABASE_URL=SUPABASE_DATABASE_URL:latest,GOOGLE_AI_API_KEY=GOOGLE_AI_API_KEY:latest,REPLICATE_API_TOKEN=REPLICATE_API_TOKEN:latest'

images:
  - 'gcr.io/$PROJECT_ID/financial-planner:latest'

timeout: '1200s'
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
