#!/bin/bash
set -e

# Load environment variables
if [ -f .env.local ]; then
    export $(cat .env.local | grep -v '^#' | xargs)
else
    echo "Error: .env.local not found"
    exit 1
fi

TRIGGER_ID="Omnifolio"

echo "Updating Cloud Build trigger $TRIGGER_ID..."

# Construct substitutions list
SUBSTITUTIONS="_NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_BETTER_AUTH_URL=${NEXT_PUBLIC_BETTER_AUTH_URL}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_COINGECKO_API_KEY=${NEXT_PUBLIC_COINGECKO_API_KEY}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_FINNHUB_API_KEY=${NEXT_PUBLIC_FINNHUB_API_KEY}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_NEWS_API_KEY=${NEXT_PUBLIC_NEWS_API_KEY}"
SUBSTITUTIONS="${SUBSTITUTIONS},_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"
SUBSTITUTIONS="${SUBSTITUTIONS},_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
SUBSTITUTIONS="${SUBSTITUTIONS},_BETTER_AUTH_URL=${BETTER_AUTH_URL}"

# Update the trigger to use cloudbuild.yaml and set substitutions
gcloud builds triggers update "$TRIGGER_ID" \
    --region=global \
    --build-config=cloudbuild.yaml \
    --substitutions="$SUBSTITUTIONS"

echo "Trigger updated successfully!"
