import { Activity } from 'lucide-react';

export interface TradingInstrument {
  symbol: string;
  name: string;
  type: 'stock' | 'index' | 'forex' | 'commodity' | 'crypto' | 'etf';
  sector?: string;
  category?: string;
  exchange?: string;
  marketCap?: string;
  peRatio?: number;
  dividendYield?: number;
  volume?: string;
  description?: string;
  ceo?: string;
  employees?: string;
  founded?: string;
  headquarters?: string;
  website?: string;
  country?: string;
  currency?: string;
  currentPrice?: number;
  eps?: number;
  revenue?: string;
  color?: string;
}

export const TRADING_DATABASE: TradingInstrument[] = [
  // Major US Stocks - FAANG+
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'Large Cap Tech',
    exchange: 'NASDAQ',
    marketCap: '$3.5T',
    peRatio: 28.5,
    dividendYield: 0.4,
    volume: '60M',
    currency: 'USD',
    currentPrice: 175.43,
    eps: 6.16,
    revenue: '$383.3B',
    description: 'Multinational technology company that designs, develops, and sells consumer electronics, computer software, and online services.',
    ceo: 'Tim Cook',
    employees: '164,000',
    founded: '1976',
    headquarters: 'Cupertino, California',
    website: 'apple.com',
    country: 'United States'
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    type: 'stock',
    sector: 'Technology',
    exchange: 'NASDAQ',
    marketCap: '$2.8T',
    peRatio: 32.1,
    dividendYield: 0.7,
    volume: '25M',
    description: 'Technology corporation that produces computer software, consumer electronics, personal computers, and related services.',
    ceo: 'Satya Nadella',
    employees: '221,000',
    founded: '1975',
    headquarters: 'Redmond, Washington',
    website: 'microsoft.com',
    country: 'United States'
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    type: 'stock',
    sector: 'Technology',
    exchange: 'NASDAQ',
    marketCap: '$2.1T',
    peRatio: 25.8,
    dividendYield: 0.0,
    volume: '30M',
    description: 'Multinational conglomerate that specializes in Internet-related services and products, primarily through Google.',
    ceo: 'Sundar Pichai',
    employees: '182,000',
    founded: '1998',
    headquarters: 'Mountain View, California',
    website: 'abc.xyz',
    country: 'United States'
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    type: 'stock',
    sector: 'Consumer Discretionary',
    exchange: 'NASDAQ',
    marketCap: '$1.7T',
    peRatio: 42.3,
    dividendYield: 0.0,
    volume: '35M',
    description: 'Multinational technology company focusing on e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence.',
    ceo: 'Andy Jassy',
    employees: '1,541,000',
    founded: '1994',
    headquarters: 'Seattle, Washington',
    website: 'amazon.com',
    country: 'United States'
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    type: 'stock',
    sector: 'Automotive',
    category: 'Electric Vehicles',
    exchange: 'NASDAQ',
    marketCap: '$800B',
    peRatio: 65.2,
    dividendYield: 0.0,
    volume: '75M',
    currency: 'USD',
    currentPrice: 250.85,
    eps: 3.85,
    revenue: '$96.8B',
    description: 'Electric vehicle and clean energy company that designs, manufactures, and sells electric cars, energy storage systems, and solar panels.',
    ceo: 'Elon Musk',
    employees: '140,000',
    founded: '2003',
    headquarters: 'Austin, Texas',
    website: 'tesla.com',
    country: 'United States'
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    type: 'stock',
    sector: 'Technology',
    exchange: 'NASDAQ',
    marketCap: '$1.3T',
    peRatio: 23.4,
    dividendYield: 0.4,
    volume: '18M',
    description: 'Technology conglomerate that owns and operates Facebook, Instagram, WhatsApp, and developing metaverse technologies.',
    ceo: 'Mark Zuckerberg',
    employees: '77,000',
    founded: '2004',
    headquarters: 'Menlo Park, California',
    website: 'meta.com',
    country: 'United States'
  },
  {
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    type: 'stock',
    sector: 'Entertainment',
    exchange: 'NASDAQ',
    marketCap: '$200B',
    peRatio: 33.7,
    dividendYield: 0.0,
    volume: '5M',
    description: 'Streaming entertainment service with over 260 million paid memberships in more than 190 countries.',
    ceo: 'Ted Sarandos',
    employees: '13,000',
    founded: '1997',
    headquarters: 'Los Gatos, California',
    website: 'netflix.com',
    country: 'United States'
  },

  // Major Banks & Financial
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    type: 'stock',
    sector: 'Financial Services',
    exchange: 'NYSE',
    marketCap: '$580B',
    peRatio: 12.1,
    dividendYield: 2.1,
    volume: '8M',
    description: 'Multinational investment bank and financial services holding company headquartered in New York City.',
    ceo: 'Jamie Dimon',
    employees: '293,000',
    founded: '1799',
    headquarters: 'New York, New York',
    website: 'jpmorganchase.com',
    country: 'United States'
  },
  {
    symbol: 'BAC',
    name: 'Bank of America Corp.',
    type: 'stock',
    sector: 'Financial Services',
    exchange: 'NYSE',
    marketCap: '$320B',
    peRatio: 13.5,
    dividendYield: 2.8,
    volume: '35M',
    description: 'Multinational investment bank and financial services holding company headquartered in Charlotte, North Carolina.',
    ceo: 'Brian Moynihan',
    employees: '216,000',
    founded: '1904',
    headquarters: 'Charlotte, North Carolina',
    website: 'bankofamerica.com',
    country: 'United States'
  },

  // Broad Market US Indices - S&P, NASDAQ, Dow Jones
  {
    symbol: 'SPX',
    name: 'S&P 500',
    type: 'index',
    category: 'US Large Cap',
    exchange: 'US',
    marketCap: '$40T',
    volume: '$300B daily',
    currency: 'USD',
    currentPrice: 4780.00,
    description: 'Market-cap weighted index of 500 largest US companies. Primary US market benchmark.',
    founded: '1957',
    country: 'United States'
  },
  {
    symbol: 'NDX',
    name: 'NASDAQ-100',
    type: 'index',
    category: 'US Tech',
    exchange: 'NASDAQ',
    marketCap: '$18T',
    volume: '$150B daily',
    currency: 'USD',
    currentPrice: 16850.00,
    description: '100 largest non-financial companies on NASDAQ. Tech-heavy growth index.',
    founded: '1985',
    country: 'United States'
  },
  {
    symbol: 'DJI',
    name: 'Dow Jones Industrial Average',
    type: 'index',
    category: 'US Blue Chip',
    exchange: 'NYSE',
    marketCap: '$12T',
    volume: '$200B daily',
    currency: 'USD',
    currentPrice: 37850.00,
    description: 'Price-weighted index of 30 prominent US companies. Oldest US stock index.',
    founded: '1896',
    country: 'United States'
  },
  {
    symbol: 'RUT',
    name: 'Russell 2000',
    type: 'index',
    category: 'US Small Cap',
    exchange: 'US',
    marketCap: '$3T',
    volume: '$80B daily',
    currency: 'USD',
    currentPrice: 2085.00,
    description: 'Small-cap stock index measuring 2000 smallest companies in Russell 3000.',
    founded: '1984',
    country: 'United States'
  },
  {
    symbol: 'VIX',
    name: 'CBOE Volatility Index',
    type: 'index',
    category: 'Volatility',
    exchange: 'CBOE',
    volume: '$10B daily',
    currency: 'USD',
    currentPrice: 14.50,
    description: 'Fear gauge measuring expected market volatility. Inversely correlated with S&P 500.',
    founded: '1993',
    country: 'United States'
  },
  
  // European Indices
  {
    symbol: 'UKX',
    name: 'FTSE 100',
    type: 'index',
    category: 'UK Large Cap',
    exchange: 'LSE',
    marketCap: '$2.5T',
    volume: '$15B daily',
    currency: 'GBP',
    currentPrice: 7650.00,
    description: 'Index of 100 largest companies listed on London Stock Exchange.',
    founded: '1984',
    country: 'United Kingdom'
  },
  {
    symbol: 'DAX',
    name: 'DAX',
    type: 'index',
    category: 'German Large Cap',
    exchange: 'XETRA',
    marketCap: '$1.8T',
    volume: '$12B daily',
    currency: 'EUR',
    currentPrice: 16850.00,
    description: '40 major German blue chip companies. Europe\'s most important equity index.',
    founded: '1988',
    country: 'Germany'
  },
  {
    symbol: 'CAC',
    name: 'CAC 40',
    type: 'index',
    category: 'French Large Cap',
    exchange: 'Euronext Paris',
    marketCap: '$2.2T',
    volume: '$8B daily',
    currency: 'EUR',
    currentPrice: 7580.00,
    description: 'Benchmark French stock index of 40 largest companies.',
    founded: '1987',
    country: 'France'
  },
  {
    symbol: 'STOXX50E',
    name: 'Euro Stoxx 50',
    type: 'index',
    category: 'Eurozone',
    exchange: 'Euronext',
    marketCap: '$4.5T',
    volume: '$25B daily',
    currency: 'EUR',
    currentPrice: 4450.00,
    description: 'Index of 50 leading blue-chip companies in the Eurozone.',
    founded: '1998',
    country: 'Eurozone'
  },
  
  // Asian Indices
  {
    symbol: 'NKY',
    name: 'Nikkei 225',
    type: 'index',
    category: 'Japanese Large Cap',
    exchange: 'TSE',
    marketCap: '$6.2T',
    volume: '$20B daily',
    currency: 'JPY',
    currentPrice: 33500.00,
    description: 'Japan\'s premier stock index of 225 large publicly-owned companies.',
    founded: '1950',
    country: 'Japan'
  },
  {
    symbol: 'HSI',
    name: 'Hang Seng',
    type: 'index',
    category: 'Hong Kong',
    exchange: 'HKEX',
    marketCap: '$4.8T',
    volume: '$12B daily',
    currency: 'HKD',
    currentPrice: 16250.00,
    description: 'Freefloat-adjusted market-cap weighted index of Hong Kong\'s largest companies.',
    founded: '1969',
    country: 'Hong Kong'
  },
  {
    symbol: 'SHCOMP',
    name: 'Shanghai Composite',
    type: 'index',
    category: 'Chinese A-Shares',
    exchange: 'SSE',
    marketCap: '$7.5T',
    volume: '$45B daily',
    currency: 'CNY',
    currentPrice: 2980.00,
    description: 'Index of all stocks traded on Shanghai Stock Exchange.',
    founded: '1991',
    country: 'China'
  },
  
  // Major ETFs - SPDR, Vanguard, iShares
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF',
    type: 'etf',
    sector: 'Diversified',
    category: 'Large Cap Blend',
    exchange: 'NYSE',
    marketCap: '$500B',
    volume: '75M',
    dividendYield: 1.3,
    currency: 'USD',
    currentPrice: 478.00,
    description: 'Oldest and most liquid ETF tracking S&P 500. 0.09% expense ratio. $500B AUM.',
    founded: '1993',
    website: 'spdrs.com',
    country: 'United States'
  },
  {
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    type: 'etf',
    sector: 'Diversified',
    category: 'Large Cap Blend',
    exchange: 'NYSE',
    marketCap: '$400B',
    volume: '5M',
    dividendYield: 1.4,
    currency: 'USD',
    currentPrice: 440.00,
    description: 'Low-cost S&P 500 tracker. 0.03% expense ratio. Popular for long-term investors.',
    founded: '2010',
    country: 'United States'
  },
  {
    symbol: 'IVV',
    name: 'iShares Core S&P 500 ETF',
    type: 'etf',
    sector: 'Diversified',
    category: 'Large Cap Blend',
    exchange: 'NYSE',
    marketCap: '$380B',
    volume: '4M',
    dividendYield: 1.3,
    currency: 'USD',
    currentPrice: 490.00,
    description: 'BlackRock\'s S&P 500 ETF. 0.03% expense ratio. Tax-efficient.',
    founded: '2000',
    country: 'United States'
  },
  {
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    type: 'etf',
    sector: 'Technology',
    category: 'Large Cap Growth',
    exchange: 'NASDAQ',
    marketCap: '$220B',
    volume: '40M',
    dividendYield: 0.6,
    currency: 'USD',
    currentPrice: 395.00,
    description: 'NASDAQ-100 tracker. Tech-heavy with FAANG stocks. 0.20% expense ratio.',
    founded: '1999',
    website: 'invesco.com',
    country: 'United States'
  },
  {
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    type: 'etf',
    sector: 'Diversified',
    category: 'Small Cap Blend',
    exchange: 'NYSE',
    marketCap: '$60B',
    volume: '35M',
    dividendYield: 1.1,
    currency: 'USD',
    currentPrice: 208.50,
    description: 'Small-cap US equity exposure. More volatile than large caps. 0.19% expense ratio.',
    founded: '2000',
    country: 'United States'
  },
  {
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    type: 'etf',
    sector: 'Diversified',
    category: 'Total Market',
    exchange: 'NYSE',
    marketCap: '$350B',
    volume: '3M',
    dividendYield: 1.4,
    currency: 'USD',
    currentPrice: 245.00,
    description: 'Entire US equity market. 3,500+ stocks. 0.03% expense ratio. Ultimate diversification.',
    founded: '2001',
    country: 'United States'
  },
  
  // Sector ETFs - SPDR Select Sector
  {
    symbol: 'XLK',
    name: 'Technology Select Sector SPDR',
    type: 'etf',
    sector: 'Technology',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$55B',
    volume: '8M',
    dividendYield: 0.7,
    currency: 'USD',
    currentPrice: 198.00,
    description: 'S&P 500 technology sector. Apple, Microsoft, NVIDIA. 0.10% expense ratio.',
    founded: '1998',
    country: 'United States'
  },
  {
    symbol: 'XLF',
    name: 'Financial Select Sector SPDR',
    type: 'etf',
    sector: 'Financial',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$42B',
    volume: '50M',
    dividendYield: 1.6,
    currency: 'USD',
    currentPrice: 38.50,
    description: 'Banks, insurance, brokers. Interest rate sensitive. 0.10% expense ratio.',
    founded: '1998',
    country: 'United States'
  },
  {
    symbol: 'XLE',
    name: 'Energy Select Sector SPDR',
    type: 'etf',
    sector: 'Energy',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$35B',
    volume: '25M',
    dividendYield: 3.2,
    currency: 'USD',
    currentPrice: 88.00,
    description: 'Oil, gas, energy companies. ExxonMobil, Chevron. 0.10% expense ratio.',
    founded: '1998',
    country: 'United States'
  },
  {
    symbol: 'XLV',
    name: 'Health Care Select Sector SPDR',
    type: 'etf',
    sector: 'Healthcare',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$38B',
    volume: '12M',
    dividendYield: 1.4,
    currency: 'USD',
    currentPrice: 145.00,
    description: 'Pharma, biotech, medical devices. Defensive sector. 0.10% expense ratio.',
    founded: '1998',
    country: 'United States'
  },
  {
    symbol: 'XLY',
    name: 'Consumer Discretionary SPDR',
    type: 'etf',
    sector: 'Consumer',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$18B',
    volume: '5M',
    dividendYield: 0.7,
    currency: 'USD',
    currentPrice: 175.00,
    description: 'Amazon, Tesla, Home Depot. Economic cycle sensitive. 0.10% expense ratio.',
    founded: '1998',
    country: 'United States'
  },
  {
    symbol: 'XLP',
    name: 'Consumer Staples SPDR',
    type: 'etf',
    sector: 'Consumer',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$15B',
    volume: '8M',
    dividendYield: 2.4,
    currency: 'USD',
    currentPrice: 78.00,
    description: 'Food, beverages, household products. Defensive. 0.10% expense ratio.',
    founded: '1998',
    country: 'United States'
  },
  {
    symbol: 'XLI',
    name: 'Industrial Select Sector SPDR',
    type: 'etf',
    sector: 'Industrial',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$16B',
    volume: '12M',
    dividendYield: 1.3,
    currency: 'USD',
    currentPrice: 115.00,
    description: 'Manufacturing, construction, transportation. 0.10% expense ratio.',
    founded: '1998',
    country: 'United States'
  },
  {
    symbol: 'XLRE',
    name: 'Real Estate Select Sector SPDR',
    type: 'etf',
    sector: 'Real Estate',
    category: 'Sector',
    exchange: 'NYSE',
    marketCap: '$5B',
    volume: '6M',
    dividendYield: 3.8,
    currency: 'USD',
    currentPrice: 40.50,
    description: 'REITs and real estate companies. High dividend yield. 0.10% expense ratio.',
    founded: '2015',
    country: 'United States'
  },
  
  // International ETFs
  {
    symbol: 'EFA',
    name: 'iShares MSCI EAFE ETF',
    type: 'etf',
    sector: 'International',
    category: 'Developed Markets',
    exchange: 'NYSE',
    marketCap: '$65B',
    volume: '20M',
    dividendYield: 3.1,
    currency: 'USD',
    currentPrice: 78.00,
    description: 'Europe, Asia, Far East developed markets. Ex-US exposure. 0.32% expense ratio.',
    founded: '2001',
    country: 'International'
  },
  {
    symbol: 'EEM',
    name: 'iShares MSCI Emerging Markets ETF',
    type: 'etf',
    sector: 'International',
    category: 'Emerging Markets',
    exchange: 'NYSE',
    marketCap: '$22B',
    volume: '35M',
    dividendYield: 2.8,
    currency: 'USD',
    currentPrice: 40.50,
    description: 'China, India, Taiwan, Brazil exposure. Higher growth, higher risk. 0.68% expense ratio.',
    founded: '2003',
    country: 'Emerging Markets'
  },
  {
    symbol: 'VWO',
    name: 'Vanguard FTSE Emerging Markets ETF',
    type: 'etf',
    sector: 'International',
    category: 'Emerging Markets',
    exchange: 'NYSE',
    marketCap: '$75B',
    volume: '12M',
    dividendYield: 3.2,
    currency: 'USD',
    currentPrice: 42.00,
    description: 'Low-cost emerging markets exposure. 5,400+ stocks. 0.08% expense ratio.',
    founded: '2005',
    country: 'Emerging Markets'
  },
  
  // Bond ETFs
  {
    symbol: 'AGG',
    name: 'iShares Core US Aggregate Bond ETF',
    type: 'etf',
    sector: 'Fixed Income',
    category: 'Bonds',
    exchange: 'NYSE',
    marketCap: '$95B',
    volume: '5M',
    dividendYield: 3.8,
    currency: 'USD',
    currentPrice: 100.00,
    description: 'Total US bond market. Investment-grade bonds. 0.03% expense ratio.',
    founded: '2003',
    country: 'United States'
  },
  {
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    type: 'etf',
    sector: 'Fixed Income',
    category: 'Bonds',
    exchange: 'NASDAQ',
    marketCap: '$45B',
    volume: '15M',
    dividendYield: 4.2,
    currency: 'USD',
    currentPrice: 92.00,
    description: 'Long-duration US treasuries. Interest rate sensitive. 0.15% expense ratio.',
    founded: '2002',
    country: 'United States'
  },
  
  // Commodity ETFs
  {
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    type: 'etf',
    sector: 'Commodities',
    category: 'Precious Metals',
    exchange: 'NYSE',
    marketCap: '$60B',
    volume: '8M',
    currency: 'USD',
    currentPrice: 195.00,
    description: 'Physical gold-backed ETF. Inflation hedge. 0.40% expense ratio.',
    founded: '2004',
    country: 'Global'
  },
  {
    symbol: 'SLV',
    name: 'iShares Silver Trust',
    type: 'etf',
    sector: 'Commodities',
    category: 'Precious Metals',
    exchange: 'NYSE',
    marketCap: '$12B',
    volume: '15M',
    currency: 'USD',
    currentPrice: 22.50,
    description: 'Physical silver-backed ETF. More volatile than gold. 0.50% expense ratio.',
    founded: '2006',
    country: 'Global'
  },
  {
    symbol: 'USO',
    name: 'United States Oil Fund',
    type: 'etf',
    sector: 'Commodities',
    category: 'Energy',
    exchange: 'NYSE',
    marketCap: '$1.5B',
    volume: '25M',
    currency: 'USD',
    currentPrice: 74.00,
    description: 'Tracks WTI crude oil prices. Not suitable for long-term holding. 0.79% expense ratio.',
    founded: '2006',
    country: 'Global'
  },

  // Major Cryptocurrencies - Top 50 by Market Cap (Data from CoinGecko, Binance, TradingView)
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$1.2T',
    volume: '$28B',
    currency: 'USD',
    currentPrice: 63500.00,
    description: 'The first decentralized cryptocurrency, created as a peer-to-peer electronic cash system. Digital gold and store of value.',
    founded: '2009',
    country: 'Decentralized'
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$380B',
    volume: '$15B',
    currency: 'USD',
    currentPrice: 3150.00,
    description: 'Decentralized blockchain platform that enables smart contracts and decentralized applications. Leading Web3 platform.',
    founded: '2015',
    country: 'Decentralized'
  },
  {
    symbol: 'USDT',
    name: 'Tether',
    type: 'crypto',
    category: 'Stablecoin',
    exchange: 'Global',
    marketCap: '$120B',
    volume: '$45B',
    currency: 'USD',
    currentPrice: 1.00,
    description: 'Most traded stablecoin pegged to the US Dollar, widely used for trading and transfers.',
    founded: '2014',
    country: 'Decentralized'
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    type: 'crypto',
    category: 'Exchange Token',
    exchange: 'Binance',
    marketCap: '$85B',
    volume: '$1.8B',
    currency: 'USD',
    currentPrice: 580.00,
    description: 'Native token of Binance ecosystem, used for trading fee discounts and BNB Chain transactions.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$68B',
    volume: '$3.2B',
    currency: 'USD',
    currentPrice: 145.00,
    description: 'High-performance blockchain supporting fast and low-cost transactions. Popular for DeFi and NFTs.',
    founded: '2020',
    country: 'Decentralized'
  },
  {
    symbol: 'USDC',
    name: 'USD Coin',
    type: 'crypto',
    category: 'Stablecoin',
    exchange: 'Global',
    marketCap: '$32B',
    volume: '$6.5B',
    currency: 'USD',
    currentPrice: 1.00,
    description: 'Fully reserved stablecoin issued by Circle, backed by US dollars and short-term US treasuries.',
    founded: '2018',
    country: 'Decentralized'
  },
  {
    symbol: 'XRP',
    name: 'XRP',
    type: 'crypto',
    category: 'Payment',
    exchange: 'Global',
    marketCap: '$30B',
    volume: '$1.5B',
    currency: 'USD',
    currentPrice: 0.52,
    description: 'Digital payment protocol designed for fast and low-cost international money transfers.',
    founded: '2012',
    country: 'Decentralized'
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    type: 'crypto',
    category: 'Meme',
    exchange: 'Global',
    marketCap: '$22B',
    volume: '$1.2B',
    currency: 'USD',
    currentPrice: 0.15,
    description: 'Popular meme cryptocurrency with strong community support. Used for tipping and microtransactions.',
    founded: '2013',
    country: 'Decentralized'
  },
  {
    symbol: 'TRX',
    name: 'TRON',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$14B',
    volume: '$800M',
    currency: 'USD',
    currentPrice: 0.16,
    description: 'Decentralized platform for content sharing and entertainment applications.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$18B',
    volume: '$450M',
    currency: 'USD',
    currentPrice: 0.51,
    description: 'Proof-of-stake blockchain platform with focus on sustainability and scalability. Academic research-based.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$13B',
    volume: '$580M',
    currency: 'USD',
    currentPrice: 34.50,
    description: 'Fast smart contracts platform with sub-second finality and high throughput.',
    founded: '2020',
    country: 'Decentralized'
  },
  {
    symbol: 'SHIB',
    name: 'Shiba Inu',
    type: 'crypto',
    category: 'Meme',
    exchange: 'Global',
    marketCap: '$11B',
    volume: '$380M',
    currency: 'USD',
    currentPrice: 0.000018,
    description: 'Ethereum-based meme token with expanding DeFi ecosystem. Dogecoin competitor.',
    founded: '2020',
    country: 'Decentralized'
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    type: 'crypto',
    category: 'Oracle',
    exchange: 'Global',
    marketCap: '$8.5B',
    volume: '$420M',
    currency: 'USD',
    currentPrice: 14.50,
    description: 'Decentralized oracle network connecting smart contracts with real-world data.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'DOT',
    name: 'Polkadot',
    type: 'crypto',
    category: 'Layer 0',
    exchange: 'Global',
    marketCap: '$9.2B',
    volume: '$250M',
    currency: 'USD',
    currentPrice: 6.80,
    description: 'Multi-chain protocol enabling different blockchains to interoperate and share information.',
    founded: '2020',
    country: 'Decentralized'
  },
  {
    symbol: 'MATIC',
    name: 'Polygon',
    type: 'crypto',
    category: 'Layer 2',
    exchange: 'Global',
    marketCap: '$7.8B',
    volume: '$320M',
    currency: 'USD',
    currentPrice: 0.85,
    description: 'Ethereum scaling solution providing faster and cheaper transactions.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'LTC',
    name: 'Litecoin',
    type: 'crypto',
    category: 'Payment',
    exchange: 'Global',
    marketCap: '$6.5B',
    volume: '$580M',
    currency: 'USD',
    currentPrice: 88.00,
    description: 'Peer-to-peer cryptocurrency created as silver to Bitcoin\'s gold. Fast transaction times.',
    founded: '2011',
    country: 'Decentralized'
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    type: 'crypto',
    category: 'DeFi',
    exchange: 'Global',
    marketCap: '$5.2B',
    volume: '$180M',
    currency: 'USD',
    currentPrice: 8.60,
    description: 'Leading decentralized exchange protocol on Ethereum. Automated market maker.',
    founded: '2018',
    country: 'Decentralized'
  },
  {
    symbol: 'ATOM',
    name: 'Cosmos',
    type: 'crypto',
    category: 'Layer 0',
    exchange: 'Global',
    marketCap: '$3.8B',
    volume: '$125M',
    currency: 'USD',
    currentPrice: 10.20,
    description: 'Internet of blockchains enabling different chains to communicate and transfer assets.',
    founded: '2019',
    country: 'Decentralized'
  },
  {
    symbol: 'XLM',
    name: 'Stellar',
    type: 'crypto',
    category: 'Payment',
    exchange: 'Global',
    marketCap: '$3.2B',
    volume: '$95M',
    currency: 'USD',
    currentPrice: 0.11,
    description: 'Open network for storing and moving money with focus on cross-border payments.',
    founded: '2014',
    country: 'Decentralized'
  },
  {
    symbol: 'XMR',
    name: 'Monero',
    type: 'crypto',
    category: 'Privacy',
    exchange: 'Global',
    marketCap: '$3.0B',
    volume: '$110M',
    currency: 'USD',
    currentPrice: 165.00,
    description: 'Privacy-focused cryptocurrency using advanced cryptography for untraceable transactions.',
    founded: '2014',
    country: 'Decentralized'
  },
  {
    symbol: 'HBAR',
    name: 'Hedera',
    type: 'crypto',
    category: 'Enterprise',
    exchange: 'Global',
    marketCap: '$2.1B',
    volume: '$65M',
    currency: 'USD',
    currentPrice: 0.06,
    description: 'Enterprise-grade distributed ledger using hashgraph consensus algorithm.',
    founded: '2018',
    country: 'Decentralized'
  },
  {
    symbol: 'NEAR',
    name: 'NEAR Protocol',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$2.5B',
    volume: '$85M',
    currency: 'USD',
    currentPrice: 4.20,
    description: 'Sharded Layer 1 blockchain designed for usability and scalability.',
    founded: '2020',
    country: 'Decentralized'
  },
  {
    symbol: 'APT',
    name: 'Aptos',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$3.8B',
    volume: '$120M',
    currency: 'USD',
    currentPrice: 8.50,
    description: 'Layer 1 blockchain built by former Meta engineers with Move programming language.',
    founded: '2022',
    country: 'Decentralized'
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    type: 'crypto',
    category: 'Layer 2',
    exchange: 'Global',
    marketCap: '$2.8B',
    volume: '$95M',
    currency: 'USD',
    currentPrice: 0.75,
    description: 'Optimistic rollup Layer 2 scaling solution for Ethereum.',
    founded: '2021',
    country: 'Decentralized'
  },
  {
    symbol: 'OP',
    name: 'Optimism',
    type: 'crypto',
    category: 'Layer 2',
    exchange: 'Global',
    marketCap: '$2.2B',
    volume: '$75M',
    currency: 'USD',
    currentPrice: 2.10,
    description: 'Ethereum Layer 2 scaling solution using optimistic rollups.',
    founded: '2021',
    country: 'Decentralized'
  },
  {
    symbol: 'FIL',
    name: 'Filecoin',
    type: 'crypto',
    category: 'Storage',
    exchange: 'Global',
    marketCap: '$2.5B',
    volume: '$110M',
    currency: 'USD',
    currentPrice: 5.20,
    description: 'Decentralized storage network turning cloud storage into an algorithmic market.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'ALGO',
    name: 'Algorand',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$1.8B',
    volume: '$65M',
    currency: 'USD',
    currentPrice: 0.22,
    description: 'Pure proof-of-stake blockchain with instant finality and low fees.',
    founded: '2019',
    country: 'Decentralized'
  },
  {
    symbol: 'VET',
    name: 'VeChain',
    type: 'crypto',
    category: 'Supply Chain',
    exchange: 'Global',
    marketCap: '$1.9B',
    volume: '$45M',
    currency: 'USD',
    currentPrice: 0.025,
    description: 'Enterprise blockchain platform for supply chain management and business processes.',
    founded: '2015',
    country: 'Decentralized'
  },
  {
    symbol: 'AAVE',
    name: 'Aave',
    type: 'crypto',
    category: 'DeFi',
    exchange: 'Global',
    marketCap: '$2.4B',
    volume: '$90M',
    currency: 'USD',
    currentPrice: 160.00,
    description: 'Decentralized lending and borrowing protocol on Ethereum.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'ICP',
    name: 'Internet Computer',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$2.1B',
    volume: '$55M',
    currency: 'USD',
    currentPrice: 4.50,
    description: 'Blockchain network extending internet functionality to host smart contracts.',
    founded: '2021',
    country: 'Decentralized'
  },
  {
    symbol: 'INJ',
    name: 'Injective',
    type: 'crypto',
    category: 'DeFi',
    exchange: 'Global',
    marketCap: '$2.6B',
    volume: '$115M',
    currency: 'USD',
    currentPrice: 28.00,
    description: 'Layer 1 blockchain optimized for decentralized finance applications.',
    founded: '2020',
    country: 'Decentralized'
  },
  {
    symbol: 'SUI',
    name: 'Sui',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$1.8B',
    volume: '$85M',
    currency: 'USD',
    currentPrice: 0.65,
    description: 'Layer 1 blockchain using Move programming language, built by Mysten Labs.',
    founded: '2023',
    country: 'Decentralized'
  },
  {
    symbol: 'GRT',
    name: 'The Graph',
    type: 'crypto',
    category: 'Infrastructure',
    exchange: 'Global',
    marketCap: '$1.5B',
    volume: '$42M',
    currency: 'USD',
    currentPrice: 0.16,
    description: 'Decentralized protocol for indexing and querying blockchain data.',
    founded: '2018',
    country: 'Decentralized'
  },
  {
    symbol: 'RUNE',
    name: 'THORChain',
    type: 'crypto',
    category: 'DeFi',
    exchange: 'Global',
    marketCap: '$1.6B',
    volume: '$58M',
    currency: 'USD',
    currentPrice: 4.80,
    description: 'Decentralized liquidity protocol for cross-chain asset swaps.',
    founded: '2018',
    country: 'Decentralized'
  },
  {
    symbol: 'FTM',
    name: 'Fantom',
    type: 'crypto',
    category: 'Layer 1',
    exchange: 'Global',
    marketCap: '$1.4B',
    volume: '$120M',
    currency: 'USD',
    currentPrice: 0.50,
    description: 'High-performance smart contract platform with instant finality.',
    founded: '2018',
    country: 'Decentralized'
  },
  {
    symbol: 'SAND',
    name: 'The Sandbox',
    type: 'crypto',
    category: 'Metaverse',
    exchange: 'Global',
    marketCap: '$1.2B',
    volume: '$95M',
    currency: 'USD',
    currentPrice: 0.52,
    description: 'Virtual world where players can build, own, and monetize gaming experiences.',
    founded: '2011',
    country: 'Decentralized'
  },
  {
    symbol: 'MANA',
    name: 'Decentraland',
    type: 'crypto',
    category: 'Metaverse',
    exchange: 'Global',
    marketCap: '$1.0B',
    volume: '$85M',
    currency: 'USD',
    currentPrice: 0.54,
    description: 'Virtual reality platform powered by Ethereum blockchain.',
    founded: '2017',
    country: 'Decentralized'
  },
  {
    symbol: 'PEPE',
    name: 'Pepe',
    type: 'crypto',
    category: 'Meme',
    exchange: 'Global',
    marketCap: '$4.2B',
    volume: '$680M',
    currency: 'USD',
    currentPrice: 0.0000098,
    description: 'Meme coin inspired by Pepe the Frog internet meme.',
    founded: '2023',
    country: 'Decentralized'
  },

  // Major Forex Pairs - Most Traded (Data from TradingView, OANDA, IG)
  {
    symbol: 'EURUSD',
    name: 'Euro to US Dollar',
    type: 'forex',
    category: 'Major Pair',
    exchange: 'FX',
    volume: '$1.5T daily',
    currency: 'USD',
    currentPrice: 1.0542,
    description: 'The most traded currency pair in the forex market, representing the Euro against the US Dollar. 24% of daily FX volume.',
    country: 'Global'
  },
  {
    symbol: 'GBPUSD',
    name: 'British Pound to US Dollar',
    type: 'forex',
    category: 'Major Pair',
    exchange: 'FX',
    volume: '$640B daily',
    currency: 'USD',
    currentPrice: 1.2650,
    description: 'Major currency pair known as "Cable", representing the British Pound against the US Dollar. 11% of daily FX volume.',
    country: 'Global'
  },
  {
    symbol: 'USDJPY',
    name: 'US Dollar to Japanese Yen',
    type: 'forex',
    category: 'Major Pair',
    exchange: 'FX',
    volume: '$900B daily',
    currency: 'JPY',
    currentPrice: 149.50,
    description: 'Major currency pair representing the US Dollar against the Japanese Yen. 14% of daily FX volume.',
    country: 'Global'
  },
  {
    symbol: 'USDCHF',
    name: 'US Dollar to Swiss Franc',
    type: 'forex',
    category: 'Major Pair',
    exchange: 'FX',
    volume: '$300B daily',
    currency: 'CHF',
    currentPrice: 0.8950,
    description: 'Major pair known as "Swissie". Swiss Franc is a safe-haven currency.',
    country: 'Global'
  },
  {
    symbol: 'AUDUSD',
    name: 'Australian Dollar to US Dollar',
    type: 'forex',
    category: 'Major Pair',
    exchange: 'FX',
    volume: '$350B daily',
    currency: 'USD',
    currentPrice: 0.6450,
    description: 'Commodity-linked currency pair, sensitive to gold and iron ore prices.',
    country: 'Global'
  },
  {
    symbol: 'USDCAD',
    name: 'US Dollar to Canadian Dollar',
    type: 'forex',
    category: 'Major Pair',
    exchange: 'FX',
    volume: '$280B daily',
    currency: 'CAD',
    currentPrice: 1.3650,
    description: 'Major pair known as "Loonie". Heavily influenced by oil prices.',
    country: 'Global'
  },
  {
    symbol: 'NZDUSD',
    name: 'New Zealand Dollar to US Dollar',
    type: 'forex',
    category: 'Major Pair',
    exchange: 'FX',
    volume: '$150B daily',
    currency: 'USD',
    currentPrice: 0.5950,
    description: 'Known as "Kiwi". Agricultural and commodity-linked currency.',
    country: 'Global'
  },
  {
    symbol: 'EURGBP',
    name: 'Euro to British Pound',
    type: 'forex',
    category: 'Cross Pair',
    exchange: 'FX',
    volume: '$180B daily',
    currency: 'GBP',
    currentPrice: 0.8350,
    description: 'Most popular cross pair, representing Euro against British Pound.',
    country: 'Global'
  },
  {
    symbol: 'EURJPY',
    name: 'Euro to Japanese Yen',
    type: 'forex',
    category: 'Cross Pair',
    exchange: 'FX',
    volume: '$220B daily',
    currency: 'JPY',
    currentPrice: 157.50,
    description: 'Popular cross pair for carry trade strategies.',
    country: 'Global'
  },
  {
    symbol: 'GBPJPY',
    name: 'British Pound to Japanese Yen',
    type: 'forex',
    category: 'Cross Pair',
    exchange: 'FX',
    volume: '$140B daily',
    currency: 'JPY',
    currentPrice: 189.20,
    description: 'Volatile cross pair popular with traders. Known as "Guppy" or "Geppy".',
    country: 'Global'
  },
  {
    symbol: 'AUDCAD',
    name: 'Australian Dollar to Canadian Dollar',
    type: 'forex',
    category: 'Cross Pair',
    exchange: 'FX',
    volume: '$45B daily',
    currency: 'CAD',
    currentPrice: 0.8800,
    description: 'Commodity-linked cross pair between two resource-rich nations.',
    country: 'Global'
  },
  {
    symbol: 'AUDNZD',
    name: 'Australian Dollar to New Zealand Dollar',
    type: 'forex',
    category: 'Cross Pair',
    exchange: 'FX',
    volume: '$35B daily',
    currency: 'NZD',
    currentPrice: 1.0850,
    description: 'Regional cross pair between neighboring Pacific economies.',
    country: 'Global'
  },
  {
    symbol: 'EURCHF',
    name: 'Euro to Swiss Franc',
    type: 'forex',
    category: 'Cross Pair',
    exchange: 'FX',
    volume: '$90B daily',
    currency: 'CHF',
    currentPrice: 0.9450,
    description: 'European cross pair, historically capped by Swiss National Bank.',
    country: 'Global'
  },

  // Precious Metals - CME, COMEX (TradingView Data)
  {
    symbol: 'GC',
    name: 'Gold Futures',
    type: 'commodity',
    category: 'Precious Metals',
    exchange: 'COMEX',
    volume: '$50B daily',
    currency: 'USD',
    currentPrice: 2045.50,
    description: 'Most liquid precious metal futures. Gold is a safe-haven asset and inflation hedge. 100 troy oz contract.',
    country: 'Global'
  },
  {
    symbol: 'SI',
    name: 'Silver Futures',
    type: 'commodity',
    category: 'Precious Metals',
    exchange: 'COMEX',
    volume: '$25B daily',
    currency: 'USD',
    currentPrice: 23.85,
    description: 'Industrial and investment metal. More volatile than gold. 5,000 troy oz contract.',
    country: 'Global'
  },
  {
    symbol: 'PL',
    name: 'Platinum Futures',
    type: 'commodity',
    category: 'Precious Metals',
    exchange: 'NYMEX',
    volume: '$5B daily',
    currency: 'USD',
    currentPrice: 965.80,
    description: 'Industrial precious metal used in catalytic converters and jewelry. 50 troy oz contract.',
    country: 'Global'
  },
  {
    symbol: 'PA',
    name: 'Palladium Futures',
    type: 'commodity',
    category: 'Precious Metals',
    exchange: 'NYMEX',
    volume: '$3B daily',
    currency: 'USD',
    currentPrice: 1125.00,
    description: 'Rare precious metal critical for automotive catalysts. 100 troy oz contract.',
    country: 'Global'
  },
  
  // Energy - NYMEX, ICE
  {
    symbol: 'CL',
    name: 'WTI Crude Oil',
    type: 'commodity',
    category: 'Energy',
    exchange: 'NYMEX',
    volume: '$100B daily',
    currency: 'USD',
    currentPrice: 78.50,
    description: 'West Texas Intermediate crude oil, benchmark for US oil pricing. 1,000 barrels contract.',
    country: 'Global'
  },
  {
    symbol: 'BRN',
    name: 'Brent Crude Oil',
    type: 'commodity',
    category: 'Energy',
    exchange: 'ICE',
    volume: '$120B daily',
    currency: 'USD',
    currentPrice: 82.25,
    description: 'International benchmark for oil pricing. Two-thirds of global oil contracts reference Brent.',
    country: 'Global'
  },
  {
    symbol: 'NG',
    name: 'Natural Gas',
    type: 'commodity',
    category: 'Energy',
    exchange: 'NYMEX',
    volume: '$35B daily',
    currency: 'USD',
    currentPrice: 3.25,
    description: 'Clean-burning fossil fuel for heating and electricity. 10,000 MMBtu contract.',
    country: 'Global'
  },
  {
    symbol: 'RB',
    name: 'RBOB Gasoline',
    type: 'commodity',
    category: 'Energy',
    exchange: 'NYMEX',
    volume: '$15B daily',
    currency: 'USD',
    currentPrice: 2.35,
    description: 'Reformulated Blendstock for Oxygenate Blending gasoline. 42,000 gallons contract.',
    country: 'Global'
  },
  {
    symbol: 'HO',
    name: 'Heating Oil',
    type: 'commodity',
    category: 'Energy',
    exchange: 'NYMEX',
    volume: '$12B daily',
    currency: 'USD',
    currentPrice: 2.65,
    description: 'Diesel fuel and heating oil futures. 42,000 gallons contract.',
    country: 'Global'
  },
  
  // Industrial Metals - LME, COMEX
  {
    symbol: 'HG',
    name: 'Copper Futures',
    type: 'commodity',
    category: 'Industrial Metals',
    exchange: 'COMEX',
    volume: '$40B daily',
    currency: 'USD',
    currentPrice: 3.85,
    description: 'Dr. Copper - economic indicator due to widespread industrial use. 25,000 lbs contract.',
    country: 'Global'
  },
  {
    symbol: 'ALI',
    name: 'Aluminum',
    type: 'commodity',
    category: 'Industrial Metals',
    exchange: 'LME',
    volume: '$15B daily',
    currency: 'USD',
    currentPrice: 2245.00,
    description: 'Lightweight metal used in construction, transportation, and packaging.',
    country: 'Global'
  },
  {
    symbol: 'ZNC',
    name: 'Zinc',
    type: 'commodity',
    category: 'Industrial Metals',
    exchange: 'LME',
    volume: '$8B daily',
    currency: 'USD',
    currentPrice: 2580.00,
    description: 'Industrial metal used for galvanizing steel and die-casting.',
    country: 'Global'
  },
  {
    symbol: 'NI',
    name: 'Nickel',
    type: 'commodity',
    category: 'Industrial Metals',
    exchange: 'LME',
    volume: '$10B daily',
    currency: 'USD',
    currentPrice: 18500.00,
    description: 'Critical for stainless steel and EV batteries. Volatile market.',
    country: 'Global'
  },
  
  // Agricultural - CBOT
  {
    symbol: 'ZC',
    name: 'Corn Futures',
    type: 'commodity',
    category: 'Agricultural',
    exchange: 'CBOT',
    volume: '$15B daily',
    currency: 'USD',
    currentPrice: 4.85,
    description: 'Most traded agricultural commodity. Used for food, feed, and ethanol. 5,000 bushels contract.',
    country: 'Global'
  },
  {
    symbol: 'ZS',
    name: 'Soybean Futures',
    type: 'commodity',
    category: 'Agricultural',
    exchange: 'CBOT',
    volume: '$20B daily',
    currency: 'USD',
    currentPrice: 13.50,
    description: 'Key oilseed crop. China is largest importer. 5,000 bushels contract.',
    country: 'Global'
  },
  {
    symbol: 'ZW',
    name: 'Wheat Futures',
    type: 'commodity',
    category: 'Agricultural',
    exchange: 'CBOT',
    volume: '$12B daily',
    currency: 'USD',
    currentPrice: 6.25,
    description: 'Global staple grain. Sensitive to weather and geopolitical events. 5,000 bushels contract.',
    country: 'Global'
  },
  {
    symbol: 'KC',
    name: 'Coffee Futures',
    type: 'commodity',
    category: 'Soft Commodities',
    exchange: 'ICE',
    volume: '$3B daily',
    currency: 'USD',
    currentPrice: 185.50,
    description: 'Arabica coffee futures. Weather-sensitive tropical commodity. 37,500 lbs contract.',
    country: 'Global'
  },
  {
    symbol: 'SB',
    name: 'Sugar Futures',
    type: 'commodity',
    category: 'Soft Commodities',
    exchange: 'ICE',
    volume: '$5B daily',
    currency: 'USD',
    currentPrice: 24.80,
    description: 'Global sugar #11 contract. Brazil is largest producer. 112,000 lbs contract.',
    country: 'Global'
  },
  {
    symbol: 'CC',
    name: 'Cocoa Futures',
    type: 'commodity',
    category: 'Soft Commodities',
    exchange: 'ICE',
    volume: '$2B daily',
    currency: 'USD',
    currentPrice: 3850.00,
    description: 'Chocolate ingredient. West Africa produces 70% of supply. 10 metric tons contract.',
    country: 'Global'
  },
  {
    symbol: 'CT',
    name: 'Cotton Futures',
    type: 'commodity',
    category: 'Soft Commodities',
    exchange: 'ICE',
    volume: '$1.5B daily',
    currency: 'USD',
    currentPrice: 82.50,
    description: 'Natural fiber for textiles. Weather-dependent. 50,000 lbs contract.',
    country: 'Global'
  },
  {
    symbol: 'LC',
    name: 'Live Cattle',
    type: 'commodity',
    category: 'Livestock',
    exchange: 'CME',
    volume: '$800M daily',
    currency: 'USD',
    currentPrice: 178.50,
    description: 'Beef cattle futures. Sensitive to feed costs and demand. 40,000 lbs contract.',
    country: 'Global'
  },
  {
    symbol: 'LH',
    name: 'Lean Hogs',
    type: 'commodity',
    category: 'Livestock',
    exchange: 'CME',
    volume: '$600M daily',
    currency: 'USD',
    currentPrice: 68.25,
    description: 'Pork futures. Major export commodity. 40,000 lbs contract.',
    country: 'Global'
  },

  // Additional Major Stocks
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    type: 'stock',
    sector: 'Technology',
    exchange: 'NASDAQ',
    marketCap: '$1.8T',
    peRatio: 65.8,
    dividendYield: 0.1,
    volume: '45M',
    description: 'Multinational technology company that designs graphics processing units for gaming and professional markets, as well as AI computing.',
    ceo: 'Jensen Huang',
    employees: '79,000',
    founded: '1993',
    headquarters: 'Santa Clara, California',
    website: 'nvidia.com',
    country: 'United States'
  },
  {
    symbol: 'V',
    name: 'Visa Inc.',
    type: 'stock',
    sector: 'Financial Services',
    exchange: 'NYSE',
    marketCap: '$500B',
    peRatio: 32.4,
    dividendYield: 0.7,
    volume: '6M',
    description: 'Multinational financial services corporation that facilitates electronic funds transfers through its payment products.',
    ceo: 'Ryan McInerney',
    employees: '26,000',
    founded: '1958',
    headquarters: 'San Francisco, California',
    website: 'visa.com',
    country: 'United States'
  },

  // Chinese Stocks (Available to European Traders)
  {
    symbol: 'NIO',
    name: 'NIO Inc.',
    type: 'stock',
    sector: 'Automotive',
    category: 'Electric Vehicles',
    exchange: 'NYSE',
    marketCap: '$16.8B',
    peRatio: 18.5,
    dividendYield: 0.0,
    volume: '25M',
    currency: 'USD',
    currentPrice: 8.45,
    eps: 0.46,
    revenue: '$7.1B',
    description: 'Chinese electric vehicle manufacturer that designs and develops electric vehicles, autonomous driving, and battery swapping technology.',
    ceo: 'William Li',
    employees: '26,763',
    founded: '2014',
    headquarters: 'Shanghai, China',
    website: 'nio.com',
    country: 'China'
  },
  {
    symbol: 'BABA',
    name: 'Alibaba Group Holding Limited',
    type: 'stock',
    sector: 'Technology',
    category: 'E-commerce',
    exchange: 'NYSE',
    marketCap: '$210B',
    peRatio: 14.2,
    dividendYield: 0.0,
    volume: '18M',
    currency: 'USD',
    currentPrice: 78.90,
    eps: 5.56,
    revenue: '$134.6B',
    description: 'Chinese multinational technology company specializing in e-commerce, retail, internet, and technology.',
    ceo: 'Daniel Zhang',
    employees: '254,941',
    founded: '1999',
    headquarters: 'Hangzhou, China',
    website: 'alibaba.com',
    country: 'China'
  },
  {
    symbol: 'JD',
    name: 'JD.com Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'E-commerce',
    exchange: 'NASDAQ',
    marketCap: '$42B',
    peRatio: 12.8,
    dividendYield: 1.2,
    volume: '8M',
    currency: 'USD',
    currentPrice: 28.50,
    eps: 2.23,
    revenue: '$151.1B',
    description: 'Chinese e-commerce company and one of the two largest B2C online retailers in China by transaction volume and revenue.',
    ceo: 'Xu Lei',
    employees: '540,000',
    founded: '1998',
    headquarters: 'Beijing, China',
    website: 'jd.com',
    country: 'China'
  },
  {
    symbol: 'BIDU',
    name: 'Baidu Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'Internet Search',
    exchange: 'NASDAQ',
    marketCap: '$32B',
    peRatio: 16.5,
    dividendYield: 0.0,
    volume: '4M',
    currency: 'USD',
    currentPrice: 91.20,
    eps: 5.53,
    revenue: '$18.1B',
    description: 'Chinese multinational technology company specializing in internet-related services and artificial intelligence.',
    ceo: 'Robin Li',
    employees: '38,000',
    founded: '2000',
    headquarters: 'Beijing, China',
    website: 'baidu.com',
    country: 'China'
  },
  {
    symbol: 'TCEHY',
    name: 'Tencent Holdings Limited',
    type: 'stock',
    sector: 'Technology',
    category: 'Gaming & Social Media',
    exchange: 'OTC',
    marketCap: '$320B',
    peRatio: 15.8,
    dividendYield: 0.4,
    volume: '2M',
    currency: 'USD',
    currentPrice: 34.75,
    eps: 2.20,
    revenue: '$86.2B',
    description: 'Chinese multinational technology and entertainment conglomerate and holding company known for WeChat and gaming.',
    ceo: 'Ma Huateng',
    employees: '116,213',
    founded: '1998',
    headquarters: 'Shenzhen, China',
    website: 'tencent.com',
    country: 'China'
  },
  {
    symbol: 'PDD',
    name: 'PDD Holdings Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'E-commerce',
    exchange: 'NASDAQ',
    marketCap: '$190B',
    peRatio: 19.4,
    dividendYield: 0.0,
    volume: '12M',
    currency: 'USD',
    currentPrice: 142.80,
    eps: 7.36,
    revenue: '$35.1B',
    description: 'Chinese e-commerce company operating the Temu marketplace and Pinduoduo platform in China.',
    ceo: 'Chen Lei',
    employees: '13,814',
    founded: '2015',
    headquarters: 'Shanghai, China',
    website: 'pdd.com',
    country: 'China'
  },
  {
    symbol: 'XPEV',
    name: 'XPeng Inc.',
    type: 'stock',
    sector: 'Automotive',
    category: 'Electric Vehicles',
    exchange: 'NYSE',
    marketCap: '$7.2B',
    peRatio: 22.1,
    dividendYield: 0.0,
    volume: '8M',
    currency: 'USD',
    currentPrice: 9.85,
    eps: 0.45,
    revenue: '$4.3B',
    description: 'Chinese electric vehicle manufacturer that designs, develops, manufactures, and markets smart electric vehicles.',
    ceo: 'He Xiaopeng',
    employees: '14,917',
    founded: '2014',
    headquarters: 'Guangzhou, China',
    website: 'xpeng.com',
    country: 'China'
  },
  {
    symbol: 'LI',
    name: 'Li Auto Inc.',
    type: 'stock',
    sector: 'Automotive',
    category: 'Electric Vehicles',
    exchange: 'NASDAQ',
    marketCap: '$21B',
    peRatio: 28.5,
    dividendYield: 0.0,
    volume: '6M',
    currency: 'USD',
    currentPrice: 20.45,
    eps: 0.72,
    revenue: '$14.2B',
    description: 'Chinese electric vehicle manufacturer focusing on extended-range electric vehicles and autonomous driving technology.',
    ceo: 'Li Xiang',
    employees: '44,585',
    founded: '2015',
    headquarters: 'Beijing, China',
    website: 'lixiang.com',
    country: 'China'
  },
  {
    symbol: 'NTES',
    name: 'NetEase Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'Gaming & Internet',
    exchange: 'NASDAQ',
    marketCap: '$52B',
    peRatio: 14.7,
    dividendYield: 2.8,
    volume: '3M',
    currency: 'USD',
    currentPrice: 78.20,
    eps: 5.32,
    revenue: '$15.6B',
    description: 'Chinese technology company providing online services centered on content, community, communication, and commerce.',
    ceo: 'William Ding',
    employees: '32,083',
    founded: '1997',
    headquarters: 'Hangzhou, China',
    website: 'netease.com',
    country: 'China'
  },
  {
    symbol: 'WB',
    name: 'Weibo Corporation',
    type: 'stock',
    sector: 'Technology',
    category: 'Social Media',
    exchange: 'NASDAQ',
    marketCap: '$2.8B',
    peRatio: 8.9,
    dividendYield: 0.0,
    volume: '1M',
    currency: 'USD',
    currentPrice: 12.45,
    eps: 1.40,
    revenue: '$1.9B',
    description: 'Chinese social media platform, often referred to as Chinese Twitter, providing microblogging services.',
    ceo: 'Wang Gaofei',
    employees: '4,700',
    founded: '2009',
    headquarters: 'Beijing, China',
    website: 'weibo.com',
    country: 'China'
  },

  // Chinese Commodities & Resources (Available to European Traders)
  // More Chinese Stocks Available to European Traders
  {
    symbol: 'JFIN',
    name: 'Jiayin Group Inc.',
    type: 'stock',
    sector: 'Financial Services',
    category: 'Fintech',
    exchange: 'NASDAQ',
    marketCap: '$180M',
    peRatio: 3.2,
    dividendYield: 0.0,
    volume: '500K',
    currency: 'USD',
    currentPrice: 4.85,
    eps: 1.52,
    revenue: '$178M',
    description: 'Chinese fintech platform providing online consumer finance services through an AI-driven platform.',
    ceo: 'Yan Dinggui',
    employees: '800',
    founded: '2011',
    headquarters: 'Shanghai, China',
    website: 'jiayin.com',
    country: 'China'
  },
  {
    symbol: 'BEKE',
    name: 'KE Holdings Inc.',
    type: 'stock',
    sector: 'Real Estate',
    category: 'PropTech',
    exchange: 'NYSE',
    marketCap: '$18B',
    peRatio: 24.3,
    dividendYield: 0.0,
    volume: '4M',
    currency: 'USD',
    currentPrice: 15.20,
    eps: 0.63,
    revenue: '$10.2B',
    description: 'Chinese real estate technology platform operator known for Beike and Lianjia brands.',
    ceo: 'Stanley Yongdong Peng',
    employees: '45,000',
    founded: '2018',
    headquarters: 'Beijing, China',
    website: 'ke.com',
    country: 'China'
  },
  {
    symbol: 'ATHM',
    name: 'Autohome Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'Automotive Internet',
    exchange: 'NYSE',
    marketCap: '$3.5B',
    peRatio: 11.2,
    dividendYield: 6.5,
    volume: '800K',
    currency: 'USD',
    currentPrice: 28.90,
    eps: 2.58,
    revenue: '$1.4B',
    description: 'Chinese automotive internet platform providing content, lead generation, and online marketplace services.',
    ceo: 'Quan Long',
    employees: '4,500',
    founded: '2005',
    headquarters: 'Beijing, China',
    website: 'autohome.com.cn',
    country: 'China'
  },
  {
    symbol: 'QD',
    name: 'Qudian Inc.',
    type: 'stock',
    sector: 'Financial Services',
    category: 'Consumer Finance',
    exchange: 'NYSE',
    marketCap: '$220M',
    peRatio: 2.8,
    dividendYield: 0.0,
    volume: '600K',
    currency: 'USD',
    currentPrice: 1.15,
    eps: 0.41,
    revenue: '$580M',
    description: 'Chinese consumer credit service platform providing online small consumer credit products.',
    ceo: 'Min Luo',
    employees: '3,200',
    founded: '2014',
    headquarters: 'Xiamen, China',
    website: 'qudian.com',
    country: 'China'
  },
  {
    symbol: 'HUYA',
    name: 'HUYA Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'Game Streaming',
    exchange: 'NYSE',
    marketCap: '$850M',
    peRatio: 18.5,
    dividendYield: 0.0,
    volume: '1.2M',
    currency: 'USD',
    currentPrice: 3.45,
    eps: 0.19,
    revenue: '$1.5B',
    description: 'Chinese game live streaming platform providing live streaming of esports, entertainment, and other content.',
    ceo: 'Dong Rongjie',
    employees: '2,800',
    founded: '2014',
    headquarters: 'Guangzhou, China',
    website: 'huya.com',
    country: 'China'
  },
  {
    symbol: 'MOMO',
    name: 'Hello Group Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'Social Entertainment',
    exchange: 'NASDAQ',
    marketCap: '$1.1B',
    peRatio: 8.7,
    dividendYield: 0.0,
    volume: '2M',
    currency: 'USD',
    currentPrice: 5.20,
    eps: 0.60,
    revenue: '$1.8B',
    description: 'Chinese social entertainment platform operator providing mobile-based social and entertainment services.',
    ceo: 'Yan Tang',
    employees: '5,500',
    founded: '2011',
    headquarters: 'Beijing, China',
    website: 'immomo.com',
    country: 'China'
  },
  {
    symbol: 'VNET',
    name: '21Vianet Group Inc.',
    type: 'stock',
    sector: 'Technology',
    category: 'Data Centers',
    exchange: 'NASDAQ',
    marketCap: '$890M',
    peRatio: 15.2,
    dividendYield: 0.0,
    volume: '900K',
    currency: 'USD',
    currentPrice: 3.85,
    eps: 0.25,
    revenue: '$1.2B',
    description: 'Chinese carrier-neutral internet data center services provider offering hosting, managed network, and cloud services.',
    ceo: 'Samuel Shen',
    employees: '6,200',
    founded: '1999',
    headquarters: 'Beijing, China',
    website: '21vianet.com',
    country: 'China'
  },
  {
    symbol: 'FXI',
    name: 'iShares China Large-Cap ETF',
    type: 'etf',
    sector: 'Diversified',
    category: 'China Exposure',
    exchange: 'NYSE',
    marketCap: '$4.2B',
    volume: '8M',
    currency: 'USD',
    currentPrice: 24.85,
    description: 'ETF that tracks the investment results of an index composed of Chinese large-cap stocks.',
    founded: '2004',
    website: 'ishares.com',
    country: 'China'
  },
  {
    symbol: 'ASHR',
    name: 'Xtrackers Harvest CSI 300 China A-Shares ETF',
    type: 'etf',
    sector: 'Diversified',
    category: 'China A-Shares',
    exchange: 'NYSE',
    marketCap: '$1.8B',
    volume: '2M',
    currency: 'USD',
    currentPrice: 28.90,
    description: 'ETF providing exposure to Chinese A-shares through the CSI 300 index of large-cap Chinese companies.',
    founded: '2013',
    website: 'xtrackers.com',
    country: 'China'
  },
  {
    symbol: 'YANG',
    name: 'Direxion Daily FTSE China Bear 3X Shares',
    type: 'etf',
    sector: 'Leveraged',
    category: 'China Bear',
    exchange: 'NYSE',
    marketCap: '$850M',
    volume: '15M',
    currency: 'USD',
    currentPrice: 18.25,
    description: 'Leveraged ETF that seeks daily investment results of 300% of the inverse of the daily performance of the FTSE China 50 Index.',
    founded: '2009',
    website: 'direxion.com',
    country: 'China'
  },

];

// Utility functions
export const getInstrumentBySymbol = (symbol: string): TradingInstrument | undefined => {
  if (!symbol) return undefined;
  return TRADING_DATABASE.find(instrument => 
    instrument.symbol.toLowerCase() === symbol.toLowerCase()
  );
};

export const getInstrumentsByType = (type: TradingInstrument['type']): TradingInstrument[] => {
  return TRADING_DATABASE.filter(instrument => instrument.type === type);
};

export const getInstrumentsBySector = (sector: string): TradingInstrument[] => {
  return TRADING_DATABASE.filter(instrument => 
    instrument.sector?.toLowerCase().includes(sector.toLowerCase())
  );
};

export const searchInstruments = (query: string): TradingInstrument[] => {
  const lowerQuery = query.toLowerCase();
  return TRADING_DATABASE.filter(instrument =>
    instrument.symbol.toLowerCase().includes(lowerQuery) ||
    instrument.name.toLowerCase().includes(lowerQuery) ||
    instrument.sector?.toLowerCase().includes(lowerQuery)
  );
};

// Alternative function name for compatibility
export const searchTradingInstruments = searchInstruments;

// Get all available symbols
export const getAllSymbols = (): string[] => {
  return TRADING_DATABASE.map(instrument => instrument.symbol);
};

// Get all unique types
export const getAllTypes = (): string[] => {
  const types = new Set(TRADING_DATABASE.map(instrument => instrument.type));
  return Array.from(types);
};

// Get all unique categories
export const getAllCategories = (): string[] => {
  // Only show relevant TradingView categories
  const relevantCategories = [
    'Large Cap Tech',
    'Large Cap Blend',
    'Large Cap Growth',
    'Small Cap Blend',
    'Total Market',
    'US Large Cap',
    'US Tech',
    'UK Large Cap',
    'German Large Cap',
    'Japanese Large Cap',
    'Developed Markets',
    'Emerging Markets',
    'Sector',
    'Bonds',
    'Precious Metals',
    'Energy',
    'Layer 1',
    'Layer 2',
    'Stablecoin',
    'Exchange Token',
    'Payment',
    'Meme',
    'Oracle',
    'Volatility'
  ];
  
  return relevantCategories;
};

// Get instrument icon based on type and symbol
export const getInstrumentIcon = (instrument: TradingInstrument) => {
  // This would return appropriate icon components based on the instrument
  // For now, returning Activity as default
  return Activity;
};

// Get instrument color based on type
export const getInstrumentColor = (instrument: TradingInstrument): string => {
  const colorMap = {
    stock: '#8b5cf6',     // Purple (matches stock portfolio)
    crypto: '#F59E0B',    // Amber
    forex: '#3B82F6',     // Blue
    commodity: '#8B5CF6', // Purple
    etf: '#06B6D4',       // Cyan
    index: '#EF4444'      // Red
  };
  
  return colorMap[instrument.type] || '#6B7280';
};

// Export all functions for compatibility
export {
  TRADING_DATABASE as tradingDatabase,
  getInstrumentBySymbol as getInstrument,
  searchInstruments as search
};
